### ISSUE TITLE
Push tag 0.1.0 to rubygems

### ISSUE THREAD

**Issue by thijsnado** [bradphelan/jasminerice#111] opened 2013-05-24 15:01 UTC
Currently getting error:

Could not find gem 'jasminerice (= 0.1.0) ruby' in the gems available on this machine.

even though tagged on github. Can you push the 0.1.0 tag to ruby gems so we won't have to use git in our Gemfile?

**Comment by jejacks0n** [comment] 2013-05-24 15:15
Duplicate of #86.

**Closed as completed by jejacks0n** 2013-05-24 15:15 UTC
